import type { WeaponSpec, WeaponTrait } from './fps-rules';
export type ShopCategory = 'weapon' | 'skin' | 'attachment' | 'rig' | 'plate' | 'vehicleSkin';
export type AttachmentSlot = 'optic' | 'magazine' | 'handling';
export interface ShopItem {
  id: string; name: string; category: ShopCategory; description: string; price: number; currency: 'credits' | 'tokens';
  tier: 'Issued' | 'Field' | 'Elite'; requiredLevel?: number; family?: number; slot?: AttachmentSlot;
  /** Scalar overrides. Traits live in `traits` so the two never resolve twice. */
  stats?: Partial<Omit<WeaponSpec, 'traits'>>; traits?: readonly WeaponTrait[];
  modifiers?: { capacity?: number; reload?: number; recoil?: number; aimFov?: number; mobility?: number };
  palette?: string[]; accent?: string; protection?: number; absorption?: number; mobility?: number; carry?: number;
}
export const ARMORY_CATALOG: readonly ShopItem[] = [
  { id: 'paint-issued', name: 'Motor pool olive', category: 'vehicleSkin', tier: 'Issued', price: 0, currency: 'credits', description: 'Issued matte olive. Fits the Utility 01 and Falcon 01; equip each vehicle separately. Cosmetic only.' },
  { id: 'paint-jungle', name: 'Jungle patrol', category: 'vehicleSkin', tier: 'Field', requiredLevel: 2, price: 650, currency: 'credits', palette: ['#37472e', '#74805c', '#202c25', '#a2a281'], description: 'A military jungle wrap with large digital blocks. Fits both vehicles. Cosmetic only.' },
  { id: 'paint-desert', name: 'Desert convoy', category: 'vehicleSkin', tier: 'Field', requiredLevel: 3, price: 750, currency: 'credits', palette: ['#b39b70', '#d2bf94', '#75654b', '#8e835e'], description: 'Sand, khaki and weathered olive across the body panels. Fits both vehicles. Cosmetic only.' },
  { id: 'paint-arctic', name: 'Arctic expedition', category: 'vehicleSkin', tier: 'Elite', requiredLevel: 4, price: 160, currency: 'tokens', palette: ['#c8d1d0', '#eef0e9', '#536571', '#81939c'], description: 'A pale expedition livery with blue-gray breakup. Fits both vehicles. Cosmetic only.' },
  { id: 'paint-blackgold', name: 'Black gold', category: 'vehicleSkin', tier: 'Elite', requiredLevel: 5, price: 180, currency: 'tokens', palette: ['#202627', '#343b3b', '#9c8048', '#c4a76d'], description: 'Charcoal panels with restrained gold geometry. A premium cosmetic wrap for either vehicle.' },
  { id: 'sar-issued', name: 'SAR 21 · Issued', category: 'weapon', family: 0, tier: 'Issued', price: 0, currency: 'credits', description: 'The starting rifle. A dependable baseline with an integrated optic.' },
  { id: 'sar-ranger', requiredLevel: 2, name: 'SAR 21 · Ranger', category: 'weapon', family: 0, tier: 'Field', price: 900, currency: 'credits', accent: '#7691a1', stats: { damage: 39, interval: .126, reload: 1.65, recoil: .016 }, description: 'A field upgrade: harder hits and steadier follow-up shots, with a slightly slower firing cycle.' },
  { id: 'sar-vanguard', requiredLevel: 3, name: 'SAR 21 · Vanguard', category: 'weapon', family: 0, tier: 'Elite', price: 240, currency: 'tokens', accent: '#d6ad52', stats: { damage: 42, capacity: 36, interval: .108, reload: 1.53, recoil: .014 }, description: 'Premium performance. +17% damage, a 36-round magazine and quicker cycling and reloads. Gold receiver accents included.' },
  { id: 'ult-issued', name: 'Ultimax · Issued', category: 'weapon', family: 1, tier: 'Issued', price: 0, currency: 'credits', description: 'The starting support weapon, with a large drum and sustained automatic fire.' },
  { id: 'ult-patrol', requiredLevel: 2, name: 'Ultimax · Patrol', category: 'weapon', family: 1, tier: 'Field', price: 1050, currency: 'credits', accent: '#8baf85', stats: { damage: 32, capacity: 50, reload: 2.1, recoil: .022, mobility: 1.02 }, description: 'A lighter patrol configuration. Faster reloads and movement in exchange for ten rounds of drum capacity.' },
  { id: 'ult-centurion', requiredLevel: 5, name: 'Ultimax · Centurion', category: 'weapon', family: 1, tier: 'Elite', price: 280, currency: 'tokens', accent: '#c79854', stats: { damage: 35, capacity: 75, interval: .079, reload: 2.1, recoil: .020 }, description: 'Premium support package. +17% damage, 75 rounds and reduced recoil. Bronze receiver accents included.' },
  { id: 'sar-marksman', requiredLevel: 6, name: 'SAR 21 · Marksman', category: 'weapon', family: 0, tier: 'Elite', price: 320, currency: 'tokens', accent: '#b8c6cf', stats: { damage: 45, capacity: 36, interval: .105, reload: 1.5, recoil: .012, ballistics: { velocity: 620, drop: 9 } }, traits: [{ kind: 'falloff', near: 45, far: 130, minScale: .75 }, { kind: 'precision', multiplier: 2.2 }], description: 'Match barrel and trigger group. Holds full damage out to 45 m instead of 30, never falls below 75%, and rewards a precise hit with 2.2x damage. Its rounds travel, so distant shots need a little lead and hold-over.' },
  { id: 'ult-bastion', requiredLevel: 7, name: 'Ultimax · Bastion', category: 'weapon', family: 1, tier: 'Elite', price: 360, currency: 'tokens', accent: '#c2b280', stats: { damage: 38, capacity: 80, interval: .076, reload: 2.0, recoil: .018, ballistics: { velocity: 520, drop: 12 } }, traits: [{ kind: 'falloff', near: 24, far: 70, minScale: .60 }, { kind: 'precision', multiplier: 1.9 }], description: 'Heavy barrel and match feed. Eighty rounds, a far longer effective band than any other support configuration, and 1.9x on a precise hit. Its rounds travel, so distant shots need a little lead and hold-over.' },
  { id: 'skin-issued', name: 'Service olive', category: 'skin', tier: 'Issued', price: 0, currency: 'credits', description: 'Original olive polymer and dark metal. Cosmetic finish only.' },
  { id: 'skin-jungle', requiredLevel: 2, name: 'Jungle pixel', category: 'skin', tier: 'Field', price: 450, currency: 'credits', palette: ['#384731', '#788063', '#192921', '#aaa78a'], description: 'An original four-tone digital jungle pattern. Cosmetic; no stat changes.' },
  { id: 'skin-urban', requiredLevel: 2, name: 'Urban graphite', category: 'skin', tier: 'Field', price: 500, currency: 'credits', palette: ['#333c46', '#77858e', '#19232d', '#b5bdc0'], description: 'Cool graphite blocks for the waterfront skyline. Cosmetic; no stat changes.' },
  { id: 'skin-gold', requiredLevel: 3, name: 'Merlion gold', category: 'skin', tier: 'Elite', price: 120, currency: 'tokens', palette: ['#c99b38', '#e5c97e', '#907035', '#f0dfa0'], description: 'A gold finish with pale geometric highlights. Cosmetic; no stat changes.' },
  { id: 'skin-orchid', requiredLevel: 4, name: 'Midnight orchid', category: 'skin', tier: 'Elite', price: 140, currency: 'tokens', palette: ['#382945', '#b66bc4', '#212335', '#67b6b8'], description: 'Violet and teal digital detailing. Cosmetic; no stat changes.' },
  { id: 'optic-reflex', name: 'Red-dot conversion', category: 'attachment', slot: 'optic', tier: 'Field', price: 350, currency: 'credits', stats: { optic: 'reflex' }, modifiers: { aimFov: 65 }, description: 'An unmagnified red dot on a replacement rail. Removes the SAR 21 integrated scope and its bridge; no stacked sights. Fits either weapon.' },
  { id: 'optic-precision', requiredLevel: 2, name: 'Precision lens kit', category: 'attachment', slot: 'optic', tier: 'Field', price: 550, currency: 'credits', stats: { optic: 'precision' }, modifiers: { aimFov: 40 }, description: 'A 1.75× picture-in-picture sight with an etched reticle and unzoomed peripheral vision. Upgrades the SAR 21 integrated lens; replaces the Ultimax red dot. Replaces any other optic attachment.' },
  { id: 'mag-quick', requiredLevel: 2, name: 'Quick-change magazine', category: 'attachment', slot: 'magazine', tier: 'Field', price: 650, currency: 'credits', modifiers: { reload: .85 }, description: 'Reload 15% faster. Occupies the magazine slot; replaces an extended magazine.' },
  { id: 'mag-extended', requiredLevel: 3, name: 'Extended magazine', category: 'attachment', slot: 'magazine', tier: 'Field', price: 700, currency: 'credits', modifiers: { capacity: 10, reload: 1.10 }, description: '+10 rounds per magazine, with 10% longer reloads. Fits either weapon.' },
  { id: 'mag-penetrator', requiredLevel: 6, name: 'Penetrator magazine', category: 'attachment', slot: 'magazine', tier: 'Elite', price: 210, currency: 'tokens', modifiers: { capacity: 10, reload: 1.10 }, traits: [{ kind: 'penetration', surfaces: 2, decay: .6 }], description: 'Hardened rounds in an extended magazine. Everything the extended magazine gives, and shots carry through up to two surfaces, losing 40% of their damage at each. Fits either weapon.' },
  { id: 'handling-stable', requiredLevel: 2, name: 'Stabilizer grip', category: 'attachment', slot: 'handling', tier: 'Field', price: 500, currency: 'credits', modifiers: { recoil: .75, mobility: .98 }, description: '25% less recoil, at a small 2% movement cost.' },
  { id: 'rig-ilbv', name: 'ILBV · Field rig', category: 'rig', tier: 'Issued', price: 0, currency: 'credits', carry: 0, mobility: 1, description: 'Integrated load-bearing vest. The starting carrying rig; armor protection comes from the insert slot.' },
  { id: 'rig-lbs', requiredLevel: 2, name: 'LBS · Enhanced', category: 'rig', tier: 'Field', price: 1000, currency: 'credits', carry: 60, mobility: .98, description: 'A modular carrying setup inspired by the LBS. +60 reserve rounds per weapon, with a 2% movement cost.' },
  { id: 'rig-sentinel', requiredLevel: 4, name: 'LBS · Sentinel', category: 'rig', tier: 'Elite', price: 180, currency: 'tokens', carry: 90, mobility: 1, description: 'Premium carrying rig: +90 reserve rounds per weapon without a movement penalty. Inserts sold separately.' },
  { id: 'plate-none', name: 'No armor inserts', category: 'plate', tier: 'Issued', price: 0, currency: 'credits', protection: 0, absorption: 0, mobility: 1, description: 'The lightest setup. The vest carries equipment but has no protection pool.' },
  { id: 'plate-soft', name: 'Soft armor inserts', category: 'plate', tier: 'Field', price: 400, currency: 'credits', protection: 35, absorption: .45, mobility: .98, description: '35 armor points. Absorbs 45% of incoming drill damage until depleted; 2% movement cost.' },
  { id: 'plate-ceramic', requiredLevel: 2, name: 'Ceramic plate set', category: 'plate', tier: 'Field', price: 900, currency: 'credits', protection: 75, absorption: .65, mobility: .94, description: '75 armor points. Absorbs 65% of drill damage until depleted; 6% movement cost.' },
  { id: 'plate-elite', requiredLevel: 4, name: 'Ceramic · Aegis', category: 'plate', tier: 'Elite', price: 160, currency: 'tokens', protection: 100, absorption: .72, mobility: .97, description: 'Premium inserts: 100 armor points, 72% absorption and a smaller 3% movement cost.' },
];
export const itemById = (id: string) => ARMORY_CATALOG.find(item => item.id === id);
export const issuedItems = ARMORY_CATALOG.filter(item => item.price === 0).map(item => item.id);
