import type { WeaponSpec, WeaponTrait } from './fps-rules';
import type { BallisticSpec } from './fps-ballistics';
export type ShopCategory = 'weapon' | 'skin' | 'attachment' | 'rig' | 'plate' | 'vehicleSkin' | 'consumable';
export type AttachmentSlot = 'optic' | 'magazine' | 'handling';
/**
 * Internal hardware a variant is built from: a barrel, a carrier, a drum. It
 * takes no attachment slot and is not sold on its own, but a variant's figures
 * are the sum of its parts rather than numbers written next to its name, so the
 * shop can say which part is responsible for which gain.
 *
 * Numeric fields are added to the platform's own figure, except `mobility`,
 * which multiplies, and `ballistics`, which replaces.
 */
export interface InternalPart {
  id: string; name: string; description: string;
  damage?: number; capacity?: number; interval?: number; reload?: number; recoil?: number; recoilRecovery?: number;
  mobility?: number; ballistics?: BallisticSpec; traits?: readonly WeaponTrait[];
}
/**
 * Hardware a premium weapon arrives with, permanently installed. It fills its
 * slot the way an attachment would and is never worse than anything buyable for
 * that slot, so a finished weapon gives up nothing by not being re-moddable.
 * The magazine slot is deliberately never fitted: it carries the ammunition
 * traits, and taking it would cost a premium weapon its penetration and burst.
 */
export interface FittedPart {
  slot: AttachmentSlot; name: string; description: string;
  stats?: Partial<Omit<WeaponSpec, 'traits'>>;
  modifiers?: { capacity?: number; reload?: number; recoil?: number; recoilRecovery?: number; aimFov?: number; mobility?: number };
  traits?: readonly WeaponTrait[];
}
export interface ShopItem {
  id: string; name: string; category: ShopCategory; description: string; price: number; currency: 'credits' | 'tokens';
  tier: 'Issued' | 'Field' | 'Elite'; requiredLevel?: number; family?: number; slot?: AttachmentSlot;
  /** Scalar overrides. Traits live in `traits` so the two never resolve twice. */
  stats?: Partial<Omit<WeaponSpec, 'traits'>>; traits?: readonly WeaponTrait[];
  /** Weapons only: the internal hardware their figures are computed from. */
  build?: readonly InternalPart[];
  /** Weapons only: hardware already installed, which fixes those slots. */
  fitted?: readonly FittedPart[];
  modifiers?: { capacity?: number; reload?: number; recoil?: number; recoilRecovery?: number; aimFov?: number; mobility?: number };
  palette?: string[]; accent?: string; protection?: number; absorption?: number; mobility?: number; carry?: number;
  /** Consumables only: what one use restores. Reserve is per equipped weapon. */
  effect?: { health?: number; armor?: number; reserve?: number };
}
export const ARMORY_CATALOG: readonly ShopItem[] = [
  { id: 'paint-issued', name: 'Motor pool olive', category: 'vehicleSkin', tier: 'Issued', price: 0, currency: 'credits', description: 'Issued matte olive. Fits the Utility 01 and Falcon 01; equip each vehicle separately. Cosmetic only.' },
  { id: 'paint-jungle', name: 'Jungle patrol', category: 'vehicleSkin', tier: 'Field', requiredLevel: 2, price: 650, currency: 'credits', palette: ['#37472e', '#74805c', '#202c25', '#a2a281'], description: 'A military jungle wrap with large digital blocks. Fits both vehicles. Cosmetic only.' },
  { id: 'paint-desert', name: 'Desert convoy', category: 'vehicleSkin', tier: 'Field', requiredLevel: 3, price: 750, currency: 'credits', palette: ['#b39b70', '#d2bf94', '#75654b', '#8e835e'], description: 'Sand, khaki and weathered olive across the body panels. Fits both vehicles. Cosmetic only.' },
  { id: 'paint-arctic', name: 'Arctic expedition', category: 'vehicleSkin', tier: 'Elite', requiredLevel: 4, price: 160, currency: 'tokens', palette: ['#c8d1d0', '#eef0e9', '#536571', '#81939c'], description: 'A pale expedition livery with blue-gray breakup. Fits both vehicles. Cosmetic only.' },
  { id: 'paint-blackgold', name: 'Black gold', category: 'vehicleSkin', tier: 'Elite', requiredLevel: 5, price: 180, currency: 'tokens', palette: ['#202627', '#343b3b', '#9c8048', '#c4a76d'], description: 'Charcoal panels with restrained gold geometry. A premium cosmetic wrap for either vehicle.' },
  { id: 'sar-issued', name: 'SAR 21 · Issued', category: 'weapon', family: 0, tier: 'Issued', price: 0, currency: 'credits', description: 'Tier 1 of 4 on this platform. The starting rifle. A dependable baseline with an integrated optic.' },
  { id: 'sar-ranger', requiredLevel: 2, name: 'SAR 21 · Ranger', category: 'weapon', family: 0, tier: 'Field', price: 900, currency: 'credits', accent: '#7691a1', build: [{ id: 'sar-chrome-barrel', name: 'Chrome-lined barrel', description: 'A lined bore that holds its accuracy through a longer service life and hits a little harder.', damage: 3 }, { id: 'sar-tuned-gas', name: 'Tuned gas port', description: 'A reworked port that cycles sooner and settles faster between shots.', interval: -.005, reload: -.15, recoil: -.002, recoilRecovery: .08 }], description: 'Tier 2 of 4 on this platform. A field upgrade: harder hits, steadier follow-up shots and a slightly quicker cycle, enough to drop a tougher target in three hits instead of four.' },
  { id: 'sar-vanguard', requiredLevel: 3, name: 'SAR 21 · Vanguard', category: 'weapon', family: 0, tier: 'Elite', price: 240, currency: 'tokens', accent: '#d6ad52', build: [{ id: 'sar-match-barrel', name: 'Match barrel and chamber', description: 'A heavier barrel and a tightened chamber. This is where the damage comes from.', damage: 14 }, { id: 'sar-extended-well', name: 'Extended magazine well', description: 'Six more rounds before a reload.', capacity: 6 }, { id: 'sar-light-carrier', name: 'Lightened bolt carrier', description: 'Less mass to move, so it cycles and reloads quicker and climbs less, and drops back onto the target sooner.', interval: -.015, reload: -.27, recoil: -.004, recoilRecovery: .12 }], description: 'Tier 3 of 4 on this platform. The first premium rifle: enough damage to drop a standard target in two hits at close range, a 36-round magazine and quicker cycling and reloads. Gold receiver accents included.', fitted: [{ slot: 'handling', name: 'Match trigger group', description: 'A tuned trigger and a counterweighted bolt carrier, fitted at the armoury. Steadier than any grip you can bolt on, returns to the sights faster than one, and it costs no movement.', modifiers: { recoil: .72, recoilRecovery: 1.28, mobility: 1 } }] },
  { id: 'ult-issued', name: 'Ultimax · Issued', category: 'weapon', family: 1, tier: 'Issued', price: 0, currency: 'credits', description: 'Tier 1 of 4 on this platform. The starting support weapon, with a large drum and sustained automatic fire.' },
  { id: 'ult-patrol', requiredLevel: 2, name: 'Ultimax · Patrol', category: 'weapon', family: 1, tier: 'Field', price: 1050, currency: 'credits', accent: '#8baf85', build: [{ id: 'ult-light-barrel', name: 'Lightened barrel and handguard', description: 'Less weight out front, so it hits harder for its class and carries easier.', damage: 4, interval: -.005, mobility: 1.02 }, { id: 'ult-drum-50', name: 'Fifty-round drum', description: 'Ten rounds fewer than issue, and quicker to change and steadier for it.', capacity: -10, reload: -.4, recoil: -.004, recoilRecovery: .06 }], description: 'Tier 2 of 4 on this platform. A lighter patrol configuration that also cycles faster. Faster reloads and movement in exchange for ten rounds of drum capacity.' },
  { id: 'ult-centurion', requiredLevel: 5, name: 'Ultimax · Centurion', category: 'weapon', family: 1, tier: 'Elite', price: 280, currency: 'tokens', accent: '#c79854', build: [{ id: 'ult-match-barrel', name: 'Heavy match barrel', description: 'A thicker profile that holds its point of aim under sustained fire.', damage: 10, recoilRecovery: .08 }, { id: 'ult-drum-75', name: 'Seventy-five-round drum', description: 'Fifteen more rounds, on a faster catch.', capacity: 15, reload: -.4 }, { id: 'ult-fast-gas', name: 'Accelerated gas system', description: 'Cycles sooner and climbs less between rounds, and settles back between them.', interval: -.01, recoil: -.006, recoilRecovery: .12 }], description: 'Tier 3 of 4 on this platform. The first premium support package: harder hits, 75 rounds and reduced recoil. Bronze receiver accents included.', fitted: [{ slot: 'handling', name: 'Reinforced feed tray and buffer', description: 'A heavier tray and a recoil buffer that soak up the drum weight shifting under sustained fire, and bring the muzzle back down between rounds.', modifiers: { recoil: .74, recoilRecovery: 1.28, mobility: 1 } }] },
  { id: 'sar-marksman', requiredLevel: 6, name: 'SAR 21 · Marksman', category: 'weapon', family: 0, tier: 'Elite', price: 320, currency: 'tokens', accent: '#b8c6cf', traits: [{ kind: 'falloff', near: 45, far: 130, minScale: .75 }, { kind: 'precision', multiplier: 2.2 }], build: [{ id: 'sar-heavy-match-barrel', name: 'Heavy match barrel', description: 'The barrel is the weapon: it carries the damage, the longer effective band, the precision and the muzzle velocity all at once.', damage: 22, ballistics: { velocity: 620, drop: 9 }, traits: [{ kind: 'falloff', near: 45, far: 130, minScale: .75 }, { kind: 'precision', multiplier: 2.2 }] }, { id: 'sar-extended-well', name: 'Extended magazine well', description: 'Six more rounds before a reload.', capacity: 6 }, { id: 'sar-comp-carrier', name: 'Competition bolt carrier', description: 'A lighter carrier on a polished rail, quicker again than the Vanguard\u2019s, and it returns to the sights fastest of any rifle carrier.', interval: -.02, reload: -.3, recoil: -.006, recoilRecovery: .18 }], description: 'Tier 4 of 4 on this platform, the top of the rifle ladder. Two hits drop any target at close range. Match barrel and trigger group hold full damage out to 45 m instead of 30, never falls below 75%, and rewards a precise hit with 2.2x damage. Its rounds travel, so distant shots need a little lead and hold-over.', fitted: [{ slot: 'optic', name: 'Fitted 1.75x match scope', description: 'A match scope bedded to the receiver rather than clamped to a rail. Same picture-in-picture sight as the lens kit, without the mounting play.', stats: { optic: 'precision' }, modifiers: { aimFov: 40 } }, { slot: 'handling', name: 'Free-floated barrel and match trigger', description: 'The handguard carries no load on the barrel, so the group holds together through a burst and the sight picture comes straight back.', modifiers: { recoil: .68, recoilRecovery: 1.38, mobility: 1 } }] },
  { id: 'ult-bastion', requiredLevel: 7, name: 'Ultimax · Bastion', category: 'weapon', family: 1, tier: 'Elite', price: 360, currency: 'tokens', accent: '#c2b280', traits: [{ kind: 'falloff', near: 24, far: 70, minScale: .60 }, { kind: 'precision', multiplier: 1.9 }], build: [{ id: 'ult-heavy-barrel', name: 'Heavy match barrel and buffered chamber', description: 'The barrel carries the damage, the longer effective band, the precision and the muzzle velocity together, and its buffered chamber keeps the drum from walking the muzzle off.', damage: 20, recoilRecovery: .10, ballistics: { velocity: 520, drop: 12 }, traits: [{ kind: 'falloff', near: 24, far: 70, minScale: .6 }, { kind: 'precision', multiplier: 1.9 }] }, { id: 'ult-drum-80', name: 'Eighty-round drum', description: 'Twenty more rounds than issue, and quicker to seat.', capacity: 20, reload: -.5 }, { id: 'ult-fast-gas-heavy', name: 'Accelerated gas system', description: 'Cycles faster than any other support configuration, climbs less doing it and recovers fastest of any support gas system.', interval: -.013, recoil: -.008, recoilRecovery: .16 }], description: 'Tier 4 of 4 on this platform, the top of the support ladder. Two hits drop a standard target at close range. Heavy barrel and match feed, eighty rounds, a far longer effective band than any other support configuration, and 1.9x on a precise hit. Its rounds travel, so distant shots need a little lead and hold-over.', fitted: [{ slot: 'handling', name: 'Bipod and buffered carrier', description: 'Built to be fired from a position rather than carried into one. The bipod and buffer hold the group where a grip cannot, and settle it fastest in the catalog.', modifiers: { recoil: .66, recoilRecovery: 1.42, mobility: 1 } }] },
  { id: 'skin-issued', name: 'Service olive', category: 'skin', tier: 'Issued', price: 0, currency: 'credits', description: 'Original olive polymer and dark metal. Cosmetic finish only.' },
  { id: 'skin-jungle', requiredLevel: 2, name: 'Jungle pixel', category: 'skin', tier: 'Field', price: 450, currency: 'credits', palette: ['#384731', '#788063', '#192921', '#aaa78a'], description: 'An original four-tone digital jungle pattern. Cosmetic; no stat changes.' },
  { id: 'skin-urban', requiredLevel: 2, name: 'Urban graphite', category: 'skin', tier: 'Field', price: 500, currency: 'credits', palette: ['#333c46', '#77858e', '#19232d', '#b5bdc0'], description: 'Cool graphite blocks for the waterfront skyline. Cosmetic; no stat changes.' },
  { id: 'skin-gold', requiredLevel: 3, name: 'Merlion gold', category: 'skin', tier: 'Elite', price: 120, currency: 'tokens', palette: ['#c99b38', '#e5c97e', '#907035', '#f0dfa0'], description: 'A gold finish with pale geometric highlights. Cosmetic; no stat changes.' },
  { id: 'skin-orchid', requiredLevel: 4, name: 'Midnight orchid', category: 'skin', tier: 'Elite', price: 140, currency: 'tokens', palette: ['#382945', '#b66bc4', '#212335', '#67b6b8'], description: 'Violet and teal digital detailing. Cosmetic; no stat changes.' },
  { id: 'optic-reflex', name: 'Red-dot conversion', category: 'attachment', slot: 'optic', tier: 'Field', price: 350, currency: 'credits', stats: { optic: 'reflex' }, modifiers: { aimFov: 65 }, description: 'An unmagnified red dot on a replacement rail. Removes the SAR 21 integrated scope and its bridge; no stacked sights. Fits either weapon.' },
  { id: 'optic-precision', requiredLevel: 2, name: 'Precision lens kit', category: 'attachment', slot: 'optic', tier: 'Field', price: 550, currency: 'credits', stats: { optic: 'precision' }, modifiers: { aimFov: 40 }, description: 'A 1.75× picture-in-picture sight with an etched reticle and unzoomed peripheral vision. Upgrades the SAR 21 integrated lens; replaces the Ultimax red dot. Replaces any other optic attachment.' },
  { id: 'mag-quick', requiredLevel: 2, name: 'Quick-change magazine', category: 'attachment', slot: 'magazine', tier: 'Field', price: 650, currency: 'credits', modifiers: { reload: .85 }, description: 'Reload 15% faster. Occupies the magazine slot; replaces an extended magazine.' },
  { id: 'mag-extended', requiredLevel: 3, name: 'Extended magazine', category: 'attachment', slot: 'magazine', tier: 'Field', price: 700, currency: 'credits', modifiers: { capacity: 10, reload: 1.10 }, description: '+10 rounds per magazine, with 10% longer reloads. Fits either weapon.' },
  { id: 'mag-penetrator', requiredLevel: 6, name: 'Penetrator magazine', category: 'attachment', slot: 'magazine', tier: 'Elite', price: 210, currency: 'tokens', modifiers: { capacity: 10, reload: 1.10 }, traits: [{ kind: 'penetration', surfaces: 2, decay: .6 }], description: 'Hardened rounds in an extended magazine. Everything the extended magazine gives, and shots carry through up to two surfaces, losing 40% of their damage at each. Fits either weapon.' },
  { id: 'mag-fragmenting', requiredLevel: 8, name: 'Fragmenting rounds', category: 'attachment', slot: 'magazine', tier: 'Elite', price: 340, currency: 'tokens', modifiers: { capacity: 10, reload: 1.10 }, traits: [{ kind: 'penetration', surfaces: 2, decay: .6 }, { kind: 'splash', radius: 2.2, minScale: .35 }], description: 'Everything the Penetrator magazine gives, and each round bursts where it stops. Anything else within 2.2 m takes a share of the damage, down to 35% at the edge. Fits either weapon.' },
  // The handling slot is the recoil slot, and it is a strict ladder: each rung
  // is at least as good as the one below on both ratings and on movement. The
  // hardware premium weapons arrive with sits above all three, which is the
  // invariant that makes a fixed slot safe to give up.
  { id: 'handling-stable', requiredLevel: 2, name: 'Stabilizer grip', category: 'attachment', slot: 'handling', tier: 'Field', price: 500, currency: 'credits', modifiers: { recoil: .75, recoilRecovery: 1.06, mobility: .98 }, description: '25% less recoil and a slightly quicker settle, at a small 2% movement cost.' },
  { id: 'handling-angled', requiredLevel: 4, name: 'Angled foregrip', category: 'attachment', slot: 'handling', tier: 'Field', price: 880, currency: 'credits', modifiers: { recoil: .75, recoilRecovery: 1.20, mobility: .99 }, description: 'A raked grip you pull the weapon into rather than hold down. The same 25% off the kick, and the muzzle drops back onto the target 20% faster between rounds. 1% movement cost.' },
  { id: 'handling-match', requiredLevel: 6, name: 'Match foregrip and buffer', category: 'attachment', slot: 'handling', tier: 'Elite', price: 240, currency: 'tokens', modifiers: { recoil: .74, recoilRecovery: 1.26, mobility: 1 }, description: 'The best grip on the shelf: a match foregrip over a buffered tube. 26% less recoil, a 26% faster settle and no movement cost. Premium weapons arrive with hardware steadier still.' },
  { id: 'rig-ilbv', name: 'ILBV · Field rig', category: 'rig', tier: 'Issued', price: 0, currency: 'credits', carry: 0, mobility: 1, description: 'Integrated load-bearing vest. The starting carrying rig; armor protection comes from the insert slot.' },
  { id: 'rig-lbs', requiredLevel: 2, name: 'LBS · Enhanced', category: 'rig', tier: 'Field', price: 1000, currency: 'credits', carry: 60, mobility: .98, description: 'A modular carrying setup inspired by the LBS. +60 reserve rounds per weapon, with a 2% movement cost.' },
  { id: 'rig-sentinel', requiredLevel: 4, name: 'LBS · Sentinel', category: 'rig', tier: 'Elite', price: 180, currency: 'tokens', carry: 90, mobility: 1, description: 'Premium carrying rig: +90 reserve rounds per weapon without a movement penalty. Inserts sold separately.' },
  // Supplies stack and are spent, so they are the shop's repeatable purchase
  // rather than a one-time unlock.
  { id: 'kit-ammo', name: 'Ammunition pouch', category: 'consumable', tier: 'Issued', price: 260, currency: 'credits', effect: { reserve: 90 }, description: 'Ninety reserve rounds for the weapon in your hands. Carried into an exercise and spent when used.' },
  { id: 'kit-dressing', name: 'Field dressing', category: 'consumable', tier: 'Field', requiredLevel: 2, price: 300, currency: 'credits', effect: { health: 45 }, description: 'Restores 45 health. Carried into an exercise and spent when used.' },
  { id: 'kit-plates', requiredLevel: 3, name: 'Spare inserts', category: 'consumable', tier: 'Field', price: 380, currency: 'credits', effect: { armor: 45 }, description: 'Restores 45 armor points, up to the protection your inserts provide.' },
  { id: 'kit-trauma', requiredLevel: 4, name: 'Trauma kit', category: 'consumable', tier: 'Elite', price: 90, currency: 'tokens', effect: { health: 100, armor: 60 }, description: 'Restores full health and 60 armor points in one use. The premium supply.' },
  { id: 'plate-none', name: 'No armor inserts', category: 'plate', tier: 'Issued', price: 0, currency: 'credits', protection: 0, absorption: 0, mobility: 1, description: 'The lightest setup. The vest carries equipment but has no protection pool.' },
  { id: 'plate-soft', name: 'Soft armor inserts', category: 'plate', tier: 'Field', price: 400, currency: 'credits', protection: 35, absorption: .45, mobility: .98, description: '35 armor points. Absorbs 45% of incoming drill damage until depleted; 2% movement cost.' },
  { id: 'plate-ceramic', requiredLevel: 2, name: 'Ceramic plate set', category: 'plate', tier: 'Field', price: 900, currency: 'credits', protection: 75, absorption: .65, mobility: .94, description: '75 armor points. Absorbs 65% of drill damage until depleted; 6% movement cost.' },
  { id: 'plate-elite', requiredLevel: 4, name: 'Ceramic · Aegis', category: 'plate', tier: 'Elite', price: 160, currency: 'tokens', protection: 100, absorption: .72, mobility: .97, description: 'Premium inserts: 100 armor points, 72% absorption and a smaller 3% movement cost.' },
];
export const itemById = (id: string) => ARMORY_CATALOG.find(item => item.id === id);
export const issuedItems = ARMORY_CATALOG.filter(item => item.price === 0).map(item => item.id);
/** Supplies stack; this caps how many of one kind a profile may hold. */
export const CONSUMABLE_LIMIT = 9;
