import { useState } from 'react';
import { ArrowRight, Check, Coins, Crosshair, Gem, Shield, CarFront, Plane, SlidersHorizontal, X } from 'lucide-react';
import { ARMORY_CATALOG, itemById, type ShopItem } from '../game/armory-catalog';
import { isEquipped, previewLoadout, resolveLoadout, SHOP_CATEGORIES } from '../game/armory-state';
import type { ArmoryStore } from '../game/use-armory';
import type { VehicleKind } from '../game/vehicle-rules';
import { progression, xpForLevel } from '../game/progression';
import ArmoryPreview from './ArmoryPreview';
import { hitDamage, opticMagnification } from '../game/fps-rules';

function Silhouette({ item }: { item: ShopItem }) {
  const armor = item.category === 'rig' || item.category === 'plate';
  return <svg className="armory-silhouette" viewBox="0 0 240 88" aria-hidden="true" style={{ color: item.palette?.[1] || item.accent || (armor ? '#889577' : '#849095') }}>
    {armor ? <><path d="M88 10h18l5 13h18l5-13h18l12 24-10 43H86L76 34z" fill="currentColor" /><path d="M97 33h46v36H97z" fill="#172225" opacity=".65" /><path d="M101 42h38m-38 9h38m-38 9h38" stroke="currentColor" strokeWidth="4" />{item.category === 'plate' && <path d="M162 28h20l8 10v39h-36V38z" fill="currentColor" stroke="#a4b9b4" />}</> : <><path d="M21 37h98l13-9h32l10 8h48v7h-48l-7 8h-53l-7 22H91l4-22H68l-2 17H47l-4-17H21z" fill="currentColor" /><path d="M70 28h52v7H70zM82 20h26v9H82z" fill="currentColor" opacity=".7" /><path d="M29 41h54m45-4h27" stroke="#1c2527" strokeWidth="3" /></>}
  </svg>;
}
function Stat({ label, value, current, unit = '', lower = false, digits = 0 }: { label: string; value: number; current: number; unit?: string; lower?: boolean; digits?: number }) {
  const delta = Number((value - current).toFixed(digits)), good = lower ? delta < 0 : delta > 0;
  return <div className="armory-stat"><span>{label}</span><b>{value.toFixed(digits)}<small>{unit}</small></b><em className={delta ? good ? 'better' : 'worse' : ''}>{delta ? `${delta > 0 ? '+' : ''}${delta.toFixed(digits)}${unit}` : '—'}</em></div>;
}
export default function ArmoryShop({ store, onEnterRange, rangeLabel = 'Marina FPS' }: { store: ArmoryStore; onEnterRange: () => void; rangeLabel?: string }) {
  const [vehicle, setVehicle] = useState<VehicleKind>('car');
  const [category, setCategory] = useState<(typeof SHOP_CATEGORIES)[number]['id']>('weapon'), [family, setFamily] = useState(0), [selectedId, setSelectedId] = useState('sar-vanguard');
  const { profile } = store;
  const level = progression(profile.xp);
  const items = ARMORY_CATALOG.filter(i => category === 'armor' ? i.category === 'rig' || i.category === 'plate' : i.category === category && (i.family === undefined || i.family === family));
  const item = items.find(i => i.id === selectedId) || items[0];
  const current = resolveLoadout(profile), preview = previewLoadout(profile, item, family), weapon = preview.weapons[family], equippedWeapon = current.weapons[family];
  const owned = profile.owned.includes(item.id), equipped = isEquipped(profile, item, family, vehicle), affordable = profile[item.currency] >= item.price;
  const vehiclePaint = category === 'vehicleSkin';
  const armor = category === 'armor', locked = !owned && level.level < (item.requiredLevel || 1);
  const nextUnlocks = ARMORY_CATALOG.filter(i => (i.requiredLevel || 1) > level.level);
  const nextLevel = Math.min(...nextUnlocks.map(i => i.requiredLevel!));
  return <section className="armory" aria-label="Equipment shop">
    <div className="armory-header"><div><span className="armory-kicker">blockplaySG / ARMORY 01</span><h2>Field exchange<span>®</span></h2><p>Choose your edge. Make it yours.</p></div><div className="armory-wallet"><span title="Earned by completing FPS exercises"><Coins size={16} /><b data-testid="credits">{profile.credits.toLocaleString()}</b><small>CR</small></span><span className="premium"><Gem size={16} /><b data-testid="tokens">{profile.tokens.toLocaleString()}</b><small>TK</small></span></div></div>
    <div className="armory-demo"><span>DEMO WALLET · No real payments</span><button onClick={store.demoTopUp}>+250 demo tokens</button></div>
    <div className="armory-progression"><div className="armory-level-badge"><b>{level.level}</b><span>LEVEL</span></div><div className="armory-xp"><div><strong>{level.rank}</strong><span>{level.xp.toLocaleString()} XP {level.level < 50 && ` / ${level.next.toLocaleString()}`}</span></div><progress value={level.progress} max={1} aria-label={level.level >= 50 ? 'Maximum level reached' : 'Progress to next level'} /><small>{level.level >= 50 ? 'Maximum level reached · all equipment level requirements met.' : nextUnlocks.length ? `Level ${nextLevel} unlocks: ${nextUnlocks.filter(i => i.requiredLevel === nextLevel).map(i => i.name).join(' · ')}` : 'All equipment level requirements met. Keep climbing to level 50.'}</small></div></div>
    <div className="armory-navigation"><div role="tablist" aria-label="Equipment categories">{SHOP_CATEGORIES.map(c => <button role="tab" id={`shop-tab-${c.id}`} aria-controls="shop-panel" key={c.id} aria-selected={category === c.id} onClick={() => setCategory(c.id)}>{c.label}{c.id === 'armor' && <Shield size={13} />}</button>)}</div></div>
    <div className="armory-body" id="shop-panel" role="tabpanel" aria-labelledby={`shop-tab-${category}`}>
      <div className="armory-main"><div className="armory-section-heading"><span>{vehiclePaint ? 'MOTOR POOL / COSMETIC WRAPS' : armor ? 'CARRYING RIGS & INSERTS' : category === 'weapon' ? 'SELECT YOUR PLATFORM' : 'CUSTOMIZE YOUR PLATFORM'}</span>{vehiclePaint && <div className="armory-family">{(['car', 'helicopter'] as const).map(kind => <button key={kind} aria-pressed={vehicle === kind} onClick={() => setVehicle(kind)}>{kind === 'car' ? 'Utility 01' : 'Falcon 01'}</button>)}</div>}{!armor && !vehiclePaint && <div className="armory-family">{['SAR 21', 'Ultimax'].map((name, i) => <button key={name} aria-pressed={family === i} onClick={() => setFamily(i)}>{name}</button>)}</div>}</div>
        <div className={`armory-showcase tier-${item.tier.toLowerCase()}`}><div className="armory-showcase-label"><span>{item.tier.toUpperCase()} / {item.category === 'skin' || vehiclePaint ? 'COSMETIC FINISH' : item.category.toUpperCase()}</span><b>{owned ? 'IN YOUR LOCKER' : 'PREVIEW'}</b></div><ArmoryPreview item={item} weapon={weapon} vehicle={vehicle} /><div className="armory-showcase-title"><h3>{item.name}</h3><span>{item.tier === 'Elite' && item.category !== 'skin' && !vehiclePaint ? 'ENHANCED STATS' : item.category === 'skin' || vehiclePaint ? 'COSMETIC ONLY' : 'FIELD EQUIPMENT'}</span></div></div>
        <div className="armory-grid">{items.map(i => <button className={`armory-item tier-${i.tier.toLowerCase()} ${i.id === item.id ? 'selected' : ''}`} key={i.id} data-item={i.id} aria-pressed={i.id === item.id} onClick={() => setSelectedId(i.id)}><div className="armory-item-top"><span>{i.tier} · LV {i.requiredLevel || 1}</span>{isEquipped(profile, i, family, vehicle) ? <span><Check size={11} /> Equipped</span> : profile.owned.includes(i.id) ? <span>Owned</span> : <span>{level.level < (i.requiredLevel || 1) ? 'LOCKED' : i.category === 'plate' ? 'INSERT' : i.category === 'rig' ? 'RIG' : 'PERMANENT'}</span>}</div>{vehiclePaint ? <div className="armory-vehicle-icon" style={{ color: i.palette?.[1] || '#819572' }}>{vehicle === 'car' ? <CarFront size={65} strokeWidth={1.1} /> : <Plane size={65} strokeWidth={1.1} />}</div> : <Silhouette item={i} />}<strong>{i.name}</strong><div className="armory-item-bottom"><span>{i.category === 'skin' || vehiclePaint ? 'Cosmetic' : i.category === 'weapon' ? `${i.stats?.damage || (i.family ? 30 : 36)} DMG` : i.category === 'plate' ? `${i.protection} AP` : i.category === 'rig' ? `+${i.carry} reserve` : i.slot}</span><b>{profile.owned.includes(i.id) ? 'OWNED' : `${i.price.toLocaleString()} ${i.currency === 'tokens' ? 'TK' : 'CR'}`}</b></div></button>)}</div>
      </div>
      <aside className="armory-details"><span className="armory-kicker">EQUIPMENT DOSSIER</span><h3>{item.name}</h3><p>{item.description}</p>{locked && <div className="armory-level-lock">LEVEL {item.requiredLevel} REQUIRED<small>{Math.max(0, xpForLevel(item.requiredLevel || 1) - level.xp).toLocaleString()} XP to unlock purchasing. Tokens do not bypass levels.</small></div>}
        <div className="armory-stat-heading"><SlidersHorizontal size={13} /> {vehiclePaint ? 'VEHICLE PAINT JOB' : armor ? 'COMPLETE ARMOR LOADOUT' : 'RESULTING WEAPON STATS'}</div><small className="armory-compare-note">{vehiclePaint ? 'Body finish only · Performance unchanged' : 'Change versus your equipped loadout'}</small>
        {vehiclePaint ? <div className="armory-vehicle-spec"><b>{vehicle === 'car' ? 'UTILITY 01 / 4×4' : 'FALCON 01 / ROTORCRAFT'}</b><p>{vehicle === 'car' ? '72 km/h top speed · WASD to drive · Space to brake' : 'Hover, climb and cruise · Space to ascend · C / Ctrl to descend'}</p><small>Unlocked wraps fit both vehicles. Equip each separately; the preview shows your selected vehicle.</small></div> : armor ? <><Stat label="Armor pool" value={preview.armor} current={current.armor} unit=" AP" /><Stat label="Absorption" value={preview.absorption * 100} current={current.absorption * 100} unit="%" /><Stat label="Rig / insert mobility" value={preview.mobility * 100} current={current.mobility * 100} unit="%" /><Stat label="SAR reserve" value={preview.weapons[0].reserve} current={current.weapons[0].reserve} /><Stat label="Ultimax reserve" value={preview.weapons[1].reserve} current={current.weapons[1].reserve} /></> : <><Stat label="Damage" value={weapon.damage} current={equippedWeapon.damage} /><Stat label="Fire rate" value={60 / weapon.interval} current={60 / equippedWeapon.interval} unit=" RPM" /><Stat label="Magazine" value={weapon.capacity} current={equippedWeapon.capacity} /><Stat label="Reload" value={weapon.reload} current={equippedWeapon.reload} unit="s" digits={2} lower /><Stat label="Recoil" value={weapon.recoil * 1000} current={equippedWeapon.recoil * 1000} digits={1} lower /><Stat label="Damage at 60 m" value={hitDamage(weapon, 60)} current={hitDamage(equippedWeapon, 60)} /><Stat label="Precision hit" value={hitDamage(weapon, 15, 'head')} current={hitDamage(equippedWeapon, 15, 'head')} /><Stat label="Sight magnification" value={opticMagnification(weapon)} current={opticMagnification(equippedWeapon)} unit="×" digits={2} /><Stat label="Movement" value={weapon.mobility * preview.mobility * 100} current={equippedWeapon.mobility * current.mobility * 100} unit="%" /></>}
        <div className="armory-purchase"><div><span>{owned ? 'PERMANENT UNLOCK' : 'ONE-TIME UNLOCK'}</span><b>{owned ? 'Owned' : `${item.price.toLocaleString()} ${item.currency === 'tokens' ? 'TK' : 'CR'}`}</b></div><button data-testid="shop-action" disabled={equipped || locked || (!owned && !affordable)} onClick={() => owned ? store.equipItem(item.id, family, vehicle) : store.buy(item.id)}>{equipped ? <><Check size={15} /> Equipped</> : owned ? <>Equip {vehiclePaint ? (vehicle === 'car' ? 'on Utility 01' : 'on Falcon 01') : armor ? 'armor' : family === 0 ? 'on SAR 21' : 'on Ultimax'} <ArrowRight size={15} /></> : locked ? `Unlocks at level ${item.requiredLevel}` : !affordable ? `Need ${item.price - profile[item.currency]} more ${item.currency === 'tokens' ? 'TK' : 'CR'}` : <>Unlock for {item.price} {item.currency === 'tokens' ? 'TK' : 'CR'} <ArrowRight size={15} /></>}</button><small>{item.currency === 'credits' && !owned ? 'Earn 250–450 CR per completed FPS exercise. Counter-fire adds 100 CR.' : 'Keep forever. Equip before entering the range.'}</small></div>
        <div className="armory-equipped"><span className="armory-kicker">CURRENT LOADOUT / {vehiclePaint ? 'MOTOR POOL' : family === 0 ? 'SAR 21' : 'ULTIMAX'}</span>{vehiclePaint ? <div className="armory-vehicle-equipped"><p>Utility 01 · {itemById(profile.vehicleSkins.car)?.name}</p><p>Falcon 01 · {itemById(profile.vehicleSkins.helicopter)?.name}</p></div> : <><b>{equippedWeapon.name}</b><p>{itemById(profile.guns[family].skin)?.name}</p>{(['optic', 'magazine', 'handling'] as const).map(slot => <div className="armory-slot" key={slot}><span>{slot}<strong>{itemById(profile.guns[family].attachments[slot] || '')?.name || (slot === 'optic' ? family === 0 ? 'Integrated 1.5× · PiP' : 'Issued red dot · 1×' : 'Standard')}</strong></span>{profile.guns[family].attachments[slot] && <button aria-label={`Remove ${slot} attachment`} onClick={() => store.remove(family, slot)}><X size={13} /></button>}</div>)}<div className="armory-rig-summary"><Shield size={16} /><span>{current.rigName}<small>{current.plateName} · {current.armor} AP</small></span></div></>}</div>
      </aside>
    </div>
    <div className="armory-footer"><div role="status">{store.saveError ? 'Browser storage unavailable. Purchases will last for this session only.' : store.message || `${ARMORY_CATALOG.length} permanent unlocks · Earn 25 XP per elimination plus completion bonuses`}<small>Fictional game stats. Protection replenishes each exercise.</small></div><button onClick={onEnterRange}><Crosshair size={17} /> Deploy to {rangeLabel} <ArrowRight size={16} /></button></div>
  </section>;
}
